# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dice_box = QtWidgets.QGridLayout()
        self.dice_box.setObjectName("dice_box")
        self.verticalLayout.addLayout(self.dice_box)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.interface_box = QtWidgets.QHBoxLayout()
        self.interface_box.setObjectName("interface_box")
        self.num_dice = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.num_dice.setMinimum(1)
        self.num_dice.setObjectName("num_dice")
        self.interface_box.addWidget(self.num_dice)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.interface_box.addWidget(self.label)
        self.dice_sides = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.dice_sides.setMinimum(1)
        self.dice_sides.setProperty("value", 6)
        self.dice_sides.setObjectName("dice_sides")
        self.interface_box.addWidget(self.dice_sides)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.interface_box.addWidget(self.label_2)
        self.roll_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.roll_btn.setObjectName("roll_btn")
        self.interface_box.addWidget(self.roll_btn)
        self.verticalLayout.addLayout(self.interface_box)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dice roller"))
        self.label.setText(_translate("MainWindow", "dice"))
        self.label_2.setText(_translate("MainWindow", "sided"))
        self.roll_btn.setText(_translate("MainWindow", "Roll"))
